version: '3.4'

services:
  dummyservice.app:
    image: iqan/dummyserviceapp
    build:
      context: .
      dockerfile: DummyService.App/Dockerfile
    environment:
      - EndpointConfiguration:ConnectionString=Endpoint=sb://iqanstest1.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Mq5adsZtZmbt0J/4eYDFa1+P3Xj8yqr06ZJD+npSC4I=
      - EndpointConfiguration:Topic=topic1
      - EndpointConfiguration:Subscription=sub1
      - ConnectionStrings:DummyDatabase=Server=db;Database=DummyDatabase;User=sa;Password=SuperSecretPassword#1;
    depends_on:
      - db
  db: 
    image: "iqan/dummydatabase"
    build:
      context: .
      dockerfile: Dockerfile-database
    environment:
      - SA_PASSWORD=SuperSecretPassword#1
      - ACCEPT_EULA=Y
  dummyservice.tests:
    image: iqan/dummyservicetests
    build:
      context: .
      dockerfile: DummyService.AcceptanceTests/Dockerfile
    environment:
      - EndpointConfiguration:ConnectionString=Endpoint=sb://iqanstest1.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Mq5adsZtZmbt0J/4eYDFa1+P3Xj8yqr06ZJD+npSC4I=
      - EndpointConfiguration:Topic=topic1
      - EndpointConfiguration:Subscription=sub1
      - ConnectionStrings:DummyDatabase=Server=db;Database=DummyDatabase;User=sa;Password=SuperSecretPassword#1;
    depends_on:
      - db
      - dummyservice.app
    command: ["./wait-for-it.sh", "db:1433", "-t", "30", "--", "dotnet", "test", "DummyService.AcceptanceTests.csproj"]